### ISSUE TITLE
Running run.sh fails with segfault

### ISSUE THREAD

**Issue by 4thedocs** [zeyiwen/mascot#14]
Hi, I tested run.sh with 2 trainingssets: a9a and one of my own. Both fail with this error message and a segfault:

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  after cub_::DeviceRadixSort::SortPairs(0): invalid device function

I am using CUDA 8 and g++ 6.3.1.

**Comment by zeyiwen** [comment]
What GPU are you using? Please try a smaller dataset, e.g. a1a. Maybe your GPU has insufficient memory.
