### ISSUE TITLE
error appears when assign some specific value to  gamma or C

### ISSUE THREAD

**Issue by ELFairyhyuk** [zeyiwen/mascot#16]
1.
Situation: train "scene" dataset with taskType=5 (i.e. train OVA SVM), with gamma=0.5, C=10
Error: While evaluate the bianry classifier (in function: evaluate() ) in file "trainClassifier.cu", segmentation cudaError appears (see the following figure) 
![image](https://user-images.githubusercontent.com/17524724/29349402-4143ff42-828c-11e7-9aa1-61d8d24a4572.png)

2.
Situation: train "mnist" dataset in OVO scheme, with C<1, gamma as default
Error: segmentation fault appears ( see the following figure) .
![image](https://user-images.githubusercontent.com/17524724/29349351-ecf8538e-828b-11e7-99ab-9264883a2464.png)

**Comment by shieldInChina** [comment]
I encountered the same problem as you @ELFairyhyuk  when I used this library with C<1 to train a binary dataset named **_ionosphere_**,  but it worked, when I tried another binary dataset **_breast-cancer_**. (both of the data were downloaded in https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html)

![image](https://user-images.githubusercontent.com/29992796/29352471-56408afc-8299-11e7-87ff-1ed746543880.png)

![image](https://user-images.githubusercontent.com/29992796/29352439-3f64cbe0-8299-11e7-9986-8e9abb732bc8.png)

**Comment by shijiashuai** [comment]
fixed in 8356259b323e0f12b213bb310684a90d474a7543
